- id: no-commit-on-branch
  name: No commit on master or main
  description: Do no allow any commit on either specified branch.
  entry: bin/no-commit-on-branch.sh
  language: script
  always_run: true
